pipeline_demo:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'demo') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'demo') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'bank') }}"
      schema: public
      threads: 4
